apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base # ベースとなるマニフェストの場所

images:
  - name: rails-image # ここは変更しない
    newTag: 0.1.1 # アプリケーションのバージョン番号(ここをgit pushする前に毎回変更することでECRのタグになり、applyでイメージ変更することができる)
    newName: 945231564387.dkr.ecr.ap-northeast-1.amazonaws.com/sample-rails # ECRレジストリのURI