apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
  labels:
    app: rails
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      volumes:
        - name: public-data
          emptyDir: {}
        - name: tmp-data
          emptyDir: {}

      initContainers:
      - name: pre-rails
        # image: [ECRのRailsイメージURL]
        image: [アカウントID].dkr.ecr.ap-northeast-1.amazonaws.com/sample-rails:0.1.0
        command: ['/bin/sh', '-c', 'cp -a /myapp/public/* /mnt/empty-dir-content/']
        volumeMounts:
          - name: public-data
            mountPath: "/mnt/empty-dir-content/"

      containers:
      - name: rails
        # image: [ECRのRailsイメージURL]
        image: [アカウントID].dkr.ecr.ap-northeast-1.amazonaws.com/sample-rails:0.1.0
        ports:
          - containerPort: 3000
        command: ['/bin/sh', '-c', 'bundle exec puma -C config/puma.rb']
        env:
          - name: DB_USERNAME
            # value: root
            value: admin
          - name: DB_PASSWORD
            value: password
          - name: DB_DATABASE
            value: myapp
          - name: DB_HOST
            value: [RDSのエンドポイント]
            # value: mysql-server
          - name: SECRET_KEY_BASE
            value: [master.keyの値]
        volumeMounts:
        - name: tmp-data
          mountPath: /myapp/tmp/sockets

      - name: nginx
        # image: [ECRのNginxイメージURL]
        image: [アカウントID].dkr.ecr.ap-northeast-1.amazonaws.com/sample-nginx
        ports:
          - containerPort: 80
        volumeMounts:
        - name: public-data
          mountPath: /myapp/public
        - name: tmp-data
          mountPath: /myapp/tmp/sockets
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 769Mi